### ISSUE TITLE
Bug: bloodhound-1 container dies during file ingestion error

### ISSUE THREAD

**Issue by t94j0** [SpecterOps/BloodHound#695]
## Description:

I'm writing an ingestor for BloodHound and when I write an invalid JSON file and attempt to ingest it, I run into an ingestion error. It's a work in progress, so it's not all there yet, and the error is expected, but I want to see where the error occurs so I know what to fix. When I run into an ingestion error, the bloodhound-1 container dies and I have to restart the container. I'd expect this to be handled gracefully and return an error on the client side instead of throwing a stack trace.

### Are you intending to fix this bug?

No

## Component(s) Affected:

- API

## Steps to Reproduce:

The specific error doesn't matter really, but you can trigger it by creating a v5 users.json with a "SpnTargets" field of:
```
"SpnTargets": [
  {
    "ComputerSID": "TODO",
    "port": 1433,
    "service": "kadmin"
  }
],
```

I can send the full users.json privately if needed.

## Expected Behavior:

Error gracefully

## Actual Behavior:

Dies

## Screenshots/Code Snippets/Sample Files:

```
bloodhound-1  | {"level":"error","time":"2024-07-13T23:42:59.299087924Z","message":"Error during processSPNTargets: unknown kind kadmin"}
bloodhound-1  | panic: assignment to entry in nil map
bloodhound-1  |
bloodhound-1  | goroutine 180 [running]:
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.IngestRelationship({0x1f88a80, 0xc00108b200}, {0x11fad9e2, 0xede250803, 0x0}, {0x7f997de34fb8, 0xc00019ae20}, {{0x0, 0x0}, {0x0, ...}, ...})
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/ingest.go:155 +0xb1
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.IngestRelationships({0x1f88a80, 0xc00108b200}, {0x7f997de34fb8, 0xc00019ae20}, {0xc0016b4000, 0x238, 0x1?})
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/ingest.go:186 +0x1a9
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.IngestBasicData({0x1f88a80, 0xc00108b200}, {{0xc00016b808, 0x35, 0x4c}, {0xc0016b4000, 0x238, 0x3a2}})
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/ingest.go:49 +0x94
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.decodeBasicData[...]({0x1f88a80, 0xc00108b200}, {0x1f6fe20, 0xc0021980f0?}, 0x1d9ba88?)  
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/decoders.go:66 +0x2fa
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.IngestWrapper({0x1f88a80?, 0xc00108b200?}, {0x1f6fe20?, 0xc0021980f0?}, {{0xc043beeb30?, 0xc00168f218?}, 0x4f2d1e?, 0xc000193590?}, 0x24?)
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/ingest.go:71 +0x105
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.ReadFileForIngest({0x1f88a80, 0xc00108b200}, {0x1f6fe20, 0xc0021980f0}, 0x0)
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/ingest.go:43 +0xca
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.(*Daemon).processIngestFile.func1({0x1f88a80, 0xc00108b200})
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/jobs.go:201 +0xe5
bloodhound-1  | github.com/specterops/bloodhound/dawgs/drivers/neo4j.(*driver).BatchOperation(0xc000690140, {0x1f78420, 0xc0011358b0}, 0xc000de9230)
bloodhound-1  |         /bloodhound/packages/go/dawgs/drivers/neo4j/driver.go:82 +0x3d6
bloodhound-1  | github.com/specterops/bloodhound/dawgs/graph.(*DatabaseSwitch).BatchOperation(0xc000690180, {0x1f78420?, 0xc0003ca500?}, 0xc000de9230)
bloodhound-1  |         /bloodhound/packages/go/dawgs/graph/switch.go:148 +0x124
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.(*Daemon).processIngestFile(0xc0005f4708, {0x1f78420, 0xc0003ca500}, {0xc000193590, 0x24}, 0x0)
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/jobs.go:195 +0x272
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.(*Daemon).processIngestTasks(0xc0005f4708, {0x1f78420, 0xc0003ca500}, {0xc000232c08, 0x1, 0x0?})
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/jobs.go:237 +0x374
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.(*Daemon).ingestAvailableTasks(0xc0005f4708)
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/datapipe.go:127 +0xd2
bloodhound-1  | github.com/specterops/bloodhound/src/daemons/datapipe.(*Daemon).Start(0xc0005f4708, {0x1f78420?, 0xc0002c20a0?})
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/datapipe/datapipe.go:153 +0x1b8
bloodhound-1  | created by github.com/specterops/bloodhound/src/daemons.(*Manager).Start in goroutine 1
bloodhound-1  |         /bloodhound/cmd/api/src/daemons/daemon.go:52 +0x225
```

## Environment Information:

BloodHound: 5.11.0

Collector: N/A

## Additional Information:

*Any additional context or information that might be helpful in understanding and diagnosing the issue.*

## Potential Solution (optional):

*If you have any ideas about what might be causing the issue or how it could be fixed, you can share them here.*

## Related Issues:

*If you've found related issues in the project's issue tracker, mention them here.*

## Contributor Checklist:

- [ X] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [ /] I have provided clear steps to reproduce the issue.
- [ X] I have included relevant environment information details.
- [ ] I have attached necessary supporting documents.
- [ ] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by superlinkx** [comment]
Thanks for the report, we squashed a few different edge cases thanks to this

**Comment by t94j0** [comment]
Great! Thanks for taking a look
